### PR TITLE
Transparent shadows

### PR DESCRIPTION
**Pull request by aparamon**
An implementation of https://github.com/josephwright/beamer/issues/466
The code is old, but it does pass the basic tests. LaTeX experts, please review!

### CODE REVIEW

**Comment by dbitouze** [comment]
I observed a very strange phenomenon with your `beamerbaseboxes.sty`: with some fonts (e.g. `Libertine`) but not others (e.g. `Latin Modern`), an extra rectangle (the color of which being the background one: nice! :) seems to be inserted between the box and its shadow, as pointed out by the following MCE:

```latex
\documentclass{beamer}

\usepackage{libertine}
% \usepackage{lmodern}

% \setbeamercolor{background canvas}{bg=yellow}

\begin{document}
\begin{frame}
  \begin{beamerboxesrounded}[shadow=true]{Theorem}
    $A = B$.
  \end{beamerboxesrounded}
\end{frame}
\end{document}
```

- **With both your `beamerbaseboxes.sty` and `libertine`:**
capture du 2018-03-20 17-51-58

- **Without both your `beamerbaseboxes.sty` or with `lmodern` instead of `libertine`:** 
capture du 2018-03-20 17-52-40


Here is my  *File List*
```
beamer.cls    2018/02/20 v3.50 A class for typesetting presentations
beamerbasemodes.sty    
etoolbox.sty    2018/02/11 v2.5e e-TeX tools for LaTeX (JAW)
beamerbasedecode.sty    
   ifpdf.sty    2017/03/15 v3.2 Provides the ifpdf switch
beamerbaseoptions.sty    
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
geometry.sty    2010/09/12 v5.6 Page Geometry
  ifvtex.sty    2016/05/16 v1.6 Detect VTeX and its facilities (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
  size11.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
 pgfcore.sty    2010/04/11 v3.0.1a (rcs-revision 1.7)
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
  pdftex.def    2018/01/08 v1.0l Graphics/color driver for pdftex
  pgfsys.sty    2014/07/09 v3.0.1a (rcs-revision 1.48)
  pgfrcs.sty    2015/08/07 v3.0.1a (rcs-revision 1.31)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
  pgfrcs.code.tex
  pgfsys.code.tex
pgfsyssoftpath.code.tex    2013/09/09  (rcs-revision 1.9)
pgfsysprotocol.code.tex    2006/10/16  (rcs-revision 1.4)
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
 pgfcore.code.tex
 xxcolor.sty    2003/10/24 ver 0.1
atbegshi.sty    2016/06/09 v1.18 At begin shipout hook (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
hyperref.sty    2018/02/06 v6.86b Hypertext links for LaTeX
hobsub-hyperref.sty    2016/05/16 v1.14 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2016/05/16 v1.14 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2016/05/16 v1.14 Construct package bundles (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
 intcalc.sty    2016/05/16 v1.2 Expandable calculations with integers (HO)
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
pdftexcmds.sty    2018/01/21 v0.26 Utility functions of pdfTeX for LuaTeX (HO)
pdfescape.sty    2016/05/16 v1.14 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2016/05/16 v1.4 Expandable calculations on big integers (HO)
  bitset.sty    2016/05/16 v1.2 Handle bit-vector datatype (HO)
uniquecounter.sty    2016/05/16 v1.3 Provide unlimited unique counter (HO)
letltxmacro.sty    2016/05/16 v1.5 Let assignment for LaTeX macros (HO)
 hopatch.sty    2016/05/16 v1.3 Wrapper for package hooks (HO)
xcolor-patch.sty    2016/05/16 xcolor patch
atveryend.sty    2016/05/16 v1.9 Hooks at the very end of document (HO)
refcount.sty    2016/05/16 v3.5 Data extraction from label references (HO)
 hycolor.sty    2016/05/16 v1.8 Color options for hyperref/bookmark (HO)
 auxhook.sty    2016/05/16 v1.4 Hooks for auxiliary files (HO)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
  pd1enc.def    2018/02/06 v6.86b Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 hpdftex.def    2018/02/06 v6.86b Hyperref driver for pdfTeX
rerunfilecheck.sty    2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
beamerbaserequires.sty    
beamerbasecompatibility.sty    
beamerbasefont.sty    
 amssymb.sty    2013/01/14 v3.01 AMS font symbols
amsfonts.sty    2013/01/14 v3.01 Basic AMSFonts support
sansmathaccent.sty    2013/03/28
filehook.sty    2011/10/12 v0.5d Hooks for input files
beamerbasetranslator.sty    
translator.sty    2018/01/04 v1.12 Easy translation of strings in LaTeX
beamerbasemisc.sty    
beamerbasetwoscreens.sty    
beamerbaseoverlay.sty    
beamerbasetitle.sty    
beamerbasesection.sty    
beamerbaseframe.sty    
beamerbaseverbatim.sty    
beamerbaseframesize.sty    
beamerbaseframecomponents.sty    
beamerbasecolor.sty    
beamerbasenotes.sty    
beamerbasetoc.sty    
beamerbasetemplates.sty    
beamerbaseauxtemplates.sty    
beamerbaseboxes.sty    
beamerbaselocalstructure.sty    
enumerate.sty    2015/07/23 v3.00 enumerate extensions (DPC)
beamerbasenavigation.sty    
beamerbasetheorems.sty    
 amsmath.sty    2017/09/02 v2.17a AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
  amsthm.sty    2017/10/31 v2.20.4
beamerbasethemes.sty    
beamerthemedefault.sty    
beamerfontthemedefault.sty    
beamercolorthemedefault.sty    
beamerinnerthemedefault.sty    
beamerouterthemedefault.sty    
libertine.sty    2018/01/03 (Bob Tennent) Supports Libertine and Biolinum fonts for all LaTeX engines.
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
textcomp.sty    2017/04/05 v2.0i Standard LaTeX package
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
mweights.sty    2017/03/30 (Bob Tennent) Support package for multiple-weight font packages. 
 fontenc.sty
fontaxes.sty    2014/03/23 v1.0d Font selection axes
LinLibertine_I.tex
  ts1cmr.fd    2014/09/29 v2.5h Standard LaTeX font definitions
OT1LinuxBiolinumT-TLF.fd    2017/03/20 (autoinst) Font definitions for OT1/LinuxBiolinumT-TLF.
supp-pdf.mkii
epstopdf-base.sty    2016/05/15 v2.6 Base part for package epstopdf
  grfext.sty    2016/05/16 v1.2 Manage graphics extensions (HO)
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
 nameref.sty    2016/05/21 v2.44 Cross-referencing by name of section
gettitlestring.sty    2016/05/16 v1.5 Cleanup title references (HO)
    test.out
    test.out
translator-basic-dictionary-English.dict    
translator-bibliography-dictionary-English.dict    
translator-environment-dictionary-English.dict    
translator-months-dictionary-English.dict    
translator-numbers-dictionary-English.dict    
translator-theorem-dictionary-English.dict    
    umsa.fd    2013/01/14 v3.01 AMS symbols A
    umsb.fd    2013/01/14 v3.01 AMS symbols B
 ***********
```

**Comment by josephwright** [comment]
Overall, the patch looks good so I'm minded to take it. The font issue comes about I think as here (as in many places in `beamer`) the sizes are absolute rather than given in font-related units. The two fonts have subtly different x-widths, and that is what leads things to be 'out'. As I say, this is no unique to this patch, and probably needs wider attention: unless there are strong objections, I'll likely merge.

**Comment by dbitouze** [comment]
@josephwright In case of `kpfonts`, I roughly managed by changing `0.2bp` in `0.6bp` in line 165 of `beamerbaseboxes.sty`:

```latex
\pgfpathrectangle{\pgfpoint{4bp}{8bp}}{\pgfpoint{\bmb@boxwidth-0.2bp}{\bmb@boxheight-2bp}}
```
Too bad such manual adjustments are necessary...

**Comment by aparamon** [comment]
@dbitouze Thank you for testing this!
I reproduce it here. Unfortunately, it's too hard for me to grok the code through the years... Might it be possible that the problem is in lacking % after { somewhere, or something like this?

**Comment by dbitouze** [comment]
@aparamon Thanks for you patch!

>Might it be possible that the problem is in lacking % after { somewhere, or something like this?

I checked them but adding it here and there where it might be missing didn't change anything.

**Comment by ghost** [comment]
And how about using the previous beamer code (which does not have the spacing problem) and add `\usebeamercolor{background canvas}` before the shadow is draw? Then the correct background colour will be used for the shadow instead of white

```
    \usebeamercolor{background canvas}
    \setbox\bmb@boxshadow=\hbox{\pgfuseshading{bmb@shadow}}%
    \setbox\bmb@boxshadowball=\hbox{\pgfuseshading{bmb@shadowball}}%
    \setbox\bmb@boxshadowballlarge=\hbox{\pgfuseshading{bmb@shadowballlarge}}%
```

(rename the attached file from .txt to .sty, github did not like it otherwise ...)
[beamerbaseboxes.txt](https://github.com/josephwright/beamer/files/1831252/beamerbaseboxes.txt)

**Comment by dbitouze** [comment]
@samcarter8 It doesn't work with nested boxes:

```latex
\documentclass{beamer}

\usepackage{kpfonts}
% \usepackage{lmodern}

\setbeamercolor{background canvas}{bg=yellow}

\begin{document}
\begin{frame}
  \begin{beamerboxesrounded}[shadow=true]{Theorem}
    \begin{minipage}{.9\linewidth}
      \begin{beamerboxesrounded}[shadow=true]{Theorem}
          $A = B$.
      \end{beamerboxesrounded}
    \end{minipage}
  \end{beamerboxesrounded}
\end{frame}
\end{document}
```

**Comment by ghost** [comment]
@dbitouze  Good point!

**Comment by aparamon** [comment]
The problem was indeed in the extra space. After an intensive pixel-hunting session, it was caught and eliminated!
Please check the updated version.

**Comment by dbitouze** [comment]
Successfully tested with several fonts: thanks!

**Pull request merged**
