### PR TITLE
Add RTL option

### PR DESCRIPTION
**Pull request by seloumi**
Hi, this create RTL option for beamer class to use with babel (lualatex engine) issue [#479](https://github.com/josephwright/beamer/issues/479#issue-331276748)

### CODE REVIEW

**Comment by josephwright** [comment]
@louisstuart96 What do you think about this?

**Comment by louisstuart96** [comment]
@josephwright I have no idea about this. The author has already published `beamer-rl` package. For me this individual package may be a better solution.

Edit: the patch uses a lot of LuaTeX-only primitives like `\textdir`, which may cause confusion if someone uses XeTeX.

**Comment by samcarter** [comment]
@seloumi two suggestions:

- because the `RTL` option adds `\babelsublr` to `pgfpicture` etc. it won't work without `babel`. Maybe it would be better if babel would be loaded automatically if this option is active instead of hoping that the users loads it?

- Could you add a test for the used engine and add an error message if this option is used with another engine than luatex?

**Comment by seloumi** [comment]
@samcarter  The option work only with `lualatex` and use babel which  changes the direction of writing   with option `bidi=basic-r`  (for xetex or pdftex  bugs in using `\special`with RTL text prevent it) 
  

-  What if the user wants to load babel with more options for example `layout=...` ?   
- Displayed error if we use another angine come from babel  (may be we need to add an error message from beamer that RTL option need luatex ?) 
  

> ! Package babel Error: The bidi method `basic' is available only in luatex

**Comment by samcarter** [comment]
@seloumi 

- One idea for passing additional options to babel: how about using the same strategy as for `xcolor` and add a documentclass option like `\documentclass[RTL,babel={layout=...}]{beamer}`? 

- The error message from babel really confused me, because my first thought was that maybe I have the wrong version of babel or something similar. It did not really occur to me that `rtl` can only be used with luatex. (and there are some evil editors that will unfortunately only show the first line of the error message, so some users won't see the hint about luatex).

**Comment by seloumi** [comment]
How about adding `ifluatex` package  to test for luatex, and a boolean `\if@beamerRTL` like this

```
\newif\ifbeamer@RTL
\beamer@RTLfalse

% RTL option

\let\beamer@activertl\@gobble

\DeclareOptionBeamer{RTL}{%
% For testing luatex if we add RTL
\RequirePackage{ifluatex}	
\ifluatex
\else
\ClassError{beamer}{RTL need to use luatex}
\fi
\beamer@RTLtrue
}
.
.
\DeclareOptionBeamer{babel}{\PassOptionsToPackage{#1}{babel}}
% or maybe like this 
%\DeclareOptionBeamer{babel}{\ifbeamer@RTL \PassOptionsToPackage{#1}{babel}\else 
%\ClassError{beamer}{babel option work with RTL}\fi}
.
.
\ifbeamer@RTL
\RequirePackage{beamerRTL} % load babel and add required stuff
\fi
```

**Comment by louisstuart96** [comment]
I have a suggestion: use macros provided by `bidi` package instead of primitives, so that the RTL functionality can be used by both XeTeX (via `bidi`) and LuaTeX (via `luabidi`). You can try this idea in `beamer-rl` package.

**Comment by seloumi** [comment]
@louisstuart96  with xetex (`bidi`) bugs of coloring RTL text still prevent adapting beamer, 
the simplest method is `babel` with lua macros `bidi=basic-r`  which change implicitely direction of text  depending on script.

**Pull request closed without merging**
