### PR TITLE
doc: \pause can mess up tikzpictures

### PR DESCRIPTION
**Pull request by hmenke**
See for example:

- https://tex.stackexchange.com/questions/21512/pause-in-tikzpicture-breaks-footline

### CODE REVIEW

**Comment by samcarter** [comment]
@hmenke Thanks for the PR!

**Comment by josephwright** [comment]
I'm not so sure about this - TIll after all wrote both `beamer` and `pgf` and in general you can use `\pause` inside TikZ structures - the `amsmath` situation is very different.

**Comment by samcarter** [comment]
> I'm not so sure about this - TIll after all wrote both `beamer` and `pgf` and in general you can use `\pause` inside TikZ structures - the `amsmath` situation is very different.

footlines etc. will vanish

**Comment by josephwright** [comment]
Sure but that's an edge case - you _cannot_ use `\pause` in `amsmath` structures at all, really.

**Comment by samcarter** [comment]
@josephwright We could experiment with patching the end of the tikzpicture, e.g. `\AtEndEnvironment{tikzpicture}{\onslide<1->}` and see if it breaks something...

**Comment by samcarter** [comment]
I think the situation for amsmath is really similar to tikzpictures. Sometimes `\pause` might work, sometimes it might give wrong results.

E.g. a user might get away with something like

```
\documentclass{beamer}
\mode<presentation> { \setbeamercovered{transparent} }

\begin{document}
\begin{frame}
\begin{align}
  A &= B \\\pause
    &= C \\\pause
    &= D
\end{align}
\end{frame}
\end{document}
```

because they are lucky and happen to use the right uncover setting. They might also get away with using `\pause` in tikzpictures if they don't have a footline. But in general, `\pause` can cause problems.

**Comment by samcarter** [comment]
(@josephwright If you feel strongly about this, I'm fine with rolling back the commit. People will anyway keep trying to use it - the difference will just be if my answers on Q&A sites will be "don't use `\pause`" or "don't use `\pause`, see the doc" :) )

**Comment by samcarter** [comment]
@josephwright Would you prefer if I would roll back the commit or do we keep it?

**Pull request merged**
