### PR TITLE
doc: showing previews of the navigations symbols

### PR DESCRIPTION
**Pull request by samcarter**
Screenshot 2022-08-31 at 17 20 11

### CODE REVIEW

**Comment by samcarter** [comment]
After reorganisation:

Screenshot 2022-08-31 at 17 31 07

**Comment by samcarter** [comment]
@josephwright  Before introducing a new dependency to the user guide, I'd love to hear your opinion on this. Is showing a preview of the navigation symbols worth adding a new dependency? 

Con: 

- new dependency for the userguide (`catchfilebetweentags` package)

Pro:

- showing a preview of the icons makes it clear which icon is which without the users having to guess from the description
- having the description and supposed effect together makes imho more sense than splitting them into two lists

**Comment by josephwright** [comment]
I'm a bit wary of `catchfilebetweentags`: let me think a bit.

**Comment by samcarter** [comment]
Sure! That why I wanted to hear your opinion :)

Alternatively, I could create a pdf with the images and then include them from there. This would avoid catchfilebetweentags

**Comment by josephwright** [comment]
I think if we need the symbols as a separate load, we should simply make a separate `.tex` file. If we were using DocStrip I'd extract independently, but we are not ...

**Comment by samcarter** [comment]
Do you mean a separate .tex file in which the navigation symbols will be stored or a separate file which renders the navigation symbols (I could just crop an empty beamer frame) and then include this as image into the doc?

**Comment by josephwright** [comment]
@samcarter  I mean a separate `.tex` that contains just the source for the symbols: we can then load it both in `beamer` and in the docs

**Comment by samcarter** [comment]
ok, sounds good. I'll do that. Thanks for your feedback!

**Comment by josephwright** [comment]
Can we make the file `.tex` :)

**Comment by samcarter** [comment]
Sure, can do that. 

... but then I'm wondering why most of the other files are .sty instead of .tex?

**Comment by josephwright** [comment]
@samcarter  Historical: I agree that they should be `.tex` (or should have been combined into one file). I'm reluctant to change the existing files, but for new stuff we should try to be a bit more precise.

**Comment by samcarter** [comment]
Ok :)

**Comment by samcarter** [comment]
(mmm, changing to .tex seems to make the test fail, I'll look into that during lunch)

**Comment by samcarter** [comment]
So, running `l3build check` seems to work fine

```
Running checks on
  beamerthemedefault (1/1)

  All checks passed
```

**Comment by samcarter** [comment]
... but when running the test locally it takes `beamerbasenavigationsymbols.tex` from my texmf tree instead of from the current folder like the other sty files. So the problem might be that the .tex file doesn't get copied.  

But wouldn't there be some kind of error message a la "file not found" in https://github.com/josephwright/beamer/actions/runs/3059485680/jobs/4938737854 ?

**Comment by samcarter** [comment]
I'm wondering if 

```
installfiles = {"**/*.cls", "**/*.sty", "**/beamericon*.*", "**/*.tex"}
```

would be safe or is there a risk that this will copy unwanted .tex files?

**Comment by josephwright** [comment]
@samcarter  There's always a risk with wildcards but I think we can live with that here

**Comment by samcarter** [comment]
OK, I pushed the commit with the wildcard. 

Ready to merge?

**Comment by samcarter** [comment]
@josephwright  Thanks! (and sorry for taking up so much of your time for this little side project!)

**Pull request merged**
