### PR TITLE
Ensure that page/frame numbers have the same width on all frames

### PR DESCRIPTION
**Pull request by samcarter**
Same as #510, the merge apparently did not like that the branch had been renamed in the mean time

### CODE REVIEW

**Comment by louisstuart96** [comment]
How about merging all the changes into a new outer theme, named like `beamerouterthemefixedwidthpageno.sty`?

**Comment by samcarter** [comment]
This would still mean that the bug is in all the standard themes. I don't think this would be useful

**Comment by louisstuart96** [comment]
@samcarter I would call it the original author's preference in template designing rather than a bug. It typesets the page numbers in a 'natrual' way, but there are some users who like to make things 'aligned'.

**Comment by samcarter** [comment]
I'm totally fine with setting the page numbers in a "natural" way, but that the date is jumping around between frame 9 and 10 cannot be a desirable layout. Making the page numbers fixed width is a quick cure to that. 

Another approach would be to position the date differently, left aligned or centred, but this would change many existing presentation, so I'd think making the page numbers fixed with is the safe alternative.

**Pull request closed without merging**
