### PR TITLE
"rtl" option to enable writing right to left in beamer 

### PR DESCRIPTION
**Pull request by seloumi**
Initially  writing RTL is based on "bidi" package and xelatex engine

### CODE REVIEW

**Comment by josephwright** [comment]
Some of the commits here seem to be changing stuff other than related to RTL: can you check back over them?

**Comment by josephwright** [comment]
I suspect the `rtl` option should be global: would that make sense? 

I wonder if the various `\ifbeamer@rtl` tests might to some extent be abstracted. For example, where the right/left skip is being set, they could be `\beamer@marginskip`, where that is a macro which expands to right or left skip as required.

There are places where an extra group is added in some cases (involving `\LR`): those could I think be handled using `\@firstofone`.

**Comment by seloumi** [comment]
Can you show  me an example where I have changed stuff  non RTL related

**Comment by josephwright** [comment]
@seloumi For example https://github.com/josephwright/beamer/pull/481/files#diff-3565eb73a12566eeef96315e82a5159c. Probably what's happened is you've based your PR on a commit that's not the HEAD of the main development line ...

**Comment by seloumi** [comment]
@josephwright 
With the version of  "beamerbaseboxes.sty" in this repository if I use xelatex  I find that shadow on rounded block do not have same height of the block (except for the first), in contrast  of the version  on my TL2018 

```latex
\documentclass{beamer}
\usefonttheme{serif}
\usetheme{Warsaw} 


\begin{document}

\begin{frame}{first frame}

\begin{block}{first}
\vrule width0pt height1cm depth1cm  
\end{block}
\begin{block}{second}
\vrule width0pt height1.5cm depth1.5cm  
\end{block}
\end{frame}

\begin{frame}{second frame}
\begin{block}{third}
\vrule width0pt height3cm depth3cm 
\end{block}
\end{frame}

\end{document}
 ```  

capture

**Comment by josephwright** [comment]
@seloumi That presumably is due to other changes (and may need addressing): I hope it's not linked to RTL.

**Comment by ghost** [comment]
@seloumi  The shadow problem might be related to https://tex.stackexchange.com/questions/445248/tikzpicture-blur-show-up-incorrectly

**Comment by louisstuart96** [comment]
@seloumi I prefer to dump all the patches to one file like `beamer-xetex-bidi.def` to be loaded automatically by `bidi` package.

**Comment by seloumi** [comment]
Thanks @louisstuart96  I think that is better, changes must be with the bidi  package

**Comment by louisstuart96** [comment]
@seloumi For the changes in inner / outer themes, you can distribute them as standalone themes like `beamerinnerthemertl.sty`. You can define new styles like
```
\defbeamertemplate{section in toc}{section numbered rtl}
```

**Pull request closed without merging**
