### PR TITLE
[Patch] Real transparency for box shadows

### PR DESCRIPTION
**Pull request by kpym**
Source: http://old.nabble.com/-Patch--Real-transparency-for-shadows-td25529391.html

I have tested it, and it makes the shadows of boxes transparent.

My current beamer is beamer 2007/03/11 cvs version 3.07

Is there any problem to apply them? Do you need more testcases? Maybe this is fixed in the latest version?

----------------------------------------
- Bitbucket: https://bitbucket.org/rivanvx/beamer/issue/161
- Originally reported by: manulopezibanez 
- Originally created at:  2011-10-13

### CODE REVIEW

**Comment by josephwright** [comment]
I've not migrated everything from BitBucket yet! This issue _will_ be overwritten with one matching the BitBucket number:  please re-log there at present. (Thinks: I'll probably need to talk to GitHub to get this one sorted: tricky)

**Comment by kpym** [comment]
Sorry, do you want that I submit a new pull request in BitBucket ?

**Comment by josephwright** [comment]
Yes: as the `beamer` docs say, the current place to log issues is on BitBucket not here. (You remind me that I need to get the ~150 remaining issues moved: it's slow work)

**Comment by josephwright** [comment]
Just a note: if I can't get this removed entirely it will end up edited into something very different (issue 161 is '[Patch] Real transparency for box shadows'  and is apparently WONTFIX!)

**Comment by josephwright** [comment]
It is sufficient to just add the two variables `\newdimen\bmb@boxwidth \newdimen\bmb@boxheight` to the beginning and to override beamers` \endbeamerboxesrounded` with the one from the patch. this can for example be done in your own beamer template by adding the `\def\endbeamerboxesrounded` part at the end of your theme. Right now I have found no issues with this approach so far...

_From Anonymous on 2012-05-03_

**Comment by josephwright** [comment]
_From Joseph Wright on     2012-05-10_

Fixed by 1213789e682c695a5c6e44debe40ad0042764f8e.

**Comment by josephwright** [comment]
_From Joseph Wright on 2012-05-13_

Back out use of real transparency of shadows

This reopens issue #161 and closes issue #192

The problem here is that while the code works for pdflatex, if fails with the latex + dvips + ps2pdf and latex + dvipdfmx routes. I suspect an issue here is actually with the `pgf` back-end, but for the moment we want something which at least works!

See e82d1ce83eca1b7dc31d099265772e9155a64bdd

**Comment by josephwright** [comment]
_From Joseph Wright on 2012-06-11_

Given the issues this causes, unless there is good evidence for a fix in the pgf drivers it has to be WONTFIX.

**Comment by josephwright** [comment]
_From Ignacio Fernández Galván on 2014-10-11_

Can't the code detect if pdflatex or latex + dvi... is being used? Or at least enable real transparency with some option (and warn the user that it will only work in some cases)?

**Comment by josephwright** [comment]
_From Joseph Wright on 2014-10-11_

That's entirely doable but then means that the outcome depends on the compilation route: if at all possible I'd rather not have that happening.

**Comment by josephwright** [comment]
_From manulopezibanez on 2015-05-13_

This patch started giving trouble:
```
./beamerouterthemeshadow.sty:97: LaTeX Error: Command \beamer@@tmpop@frametitle@shadow theme already defined. Or name \end... illegal, see p.192 of the manual.
```
but I haven't had time to find a fix. However, the output still looks right (with pdflatex).
```
Document Class: beamer 2012/10/15 development version 3.24 A class for typesetting presentations (rcs-revision 24853e6b98cf)
```

**Comment by josephwright** [comment]
_From manulopezibanez on 2015-05-13_

Ah no, this was my mistake. It still works flawlessly. Just add the files to your current directory.

I'm sure that the whole files are not needed, but it is difficult for me to understand what is the precise fix here. If someone could produce a smaller fix that would be very much appreciated.

**Comment by josephwright** [comment]
[Note: history here heavily edited to preserve issue number trail from BitBucket-

**Pull request closed without merging**
