### PR TITLE
simplify decision tree for `\beamer@howtotreatframe`

### LINKED ISSUE #866: Under `\includeonlyframes`, frames without a label are still typeset (only to be discarded)
Consider this minimal repro:

```tex
\documentclass{beamer}

\begin{document}
\includeonlyframes{good}
\begin{frame}[label=bad]
        1111111111111111111111111111111111111111111111111111111111111111
\end{frame}
\begin{frame}
        2222222222222222222222222222222222222222222222222222222222222222
\end{frame}
\end{document}
```

Each of the frames has an overfull hbox if typeset normally. Compiling this source yields an "overfull hbox" warning once, for the second slide. It seems the slide with a label is somehow properly skipped, but the slide without a label at all is typeset and then discarded?

This is a problem when preparing a presentation with slides that compile slowly: even when using `\includeonlyframes`, they are still compiled, unless you label all slides (and then you get "multiply-defined label" warnings if using the same label for each).

### LINKED ISSUE #872: `allowframebreaks` is not honored for labeled slides
Noticed while investigating #866 

```latex
\documentclass{beamer}
\begin{document}
\begin{frame}[label=x,allowframebreaks]
1
  \vskip20cm
2
\end{frame}
\begin{frame}[allowframebreaks]
1
  \vskip20cm
2
\end{frame}
\end{document}
```
The second slide is broken up, the first is not.

### LINKED ISSUE #873: Labeled `fragile=singleslide` frames are shown despite `<all:0>`
Noticed while investigating #866.

```latex
\documentclass{beamer}
\begin{document}
\begin{frame}<all:0>[label=t,fragile=singleslide]
  1
\end{frame}
\begin{frame}<all:0>[fragile=singleslide]
  2
\end{frame}
\end{document}
```

The first frame is shown (incorrectly), the second is not.

### PR DESCRIPTION
**Pull request by amonakov**
Expanding the frame environment relies on one of the following macros:

- `\beamer@doseveralframes` handles the "common case"

- `\beamer@doexternalframe` handles fragile frames, internally invoking the above macro when \frame is invoked recursively with fragile=false

- `\beamer@dosingleframe` handles fragile=singleslide frames without writing an intermediate file, so it doesn't invoke @doseveralframes and the frame cannot be reused via \againframe

- `\beamer@autobreakframe` handles allowframebreaks frames

- `\beamer@donoframe` typesets the frame in a temporary box, which is then discarded

Beamer used to choose between them by first branching on presence of a label, and when a label is NOT present, also by testing overlay specification to see if it yields no slides, via the following tree:

    if (no label)
        if (overlay specification not empty)
            if fragile=singleslide
                \beamer@dosingleframe
            elif allowframebreaks
                \beamer@autobreakframe
            elif fragile
                \beamer@doexternalframe
            else
                \beamer@doseveralframes
            fi
        else # empty overlay specification
            \beamer@donoframe
        fi
    else # has label
        if fragile
            \beamer@doexternalframe
        elif fragile=singleslide
            \beamer@dosingleframe
        else
            \beamer@doseveralframes
        fi
    fi

This structure is confusing and leads to bugs such as #872 (allowframebreaks is not handled in presence of a label) and #873 (labeled fragile=singleslide frame shown despite `<all:0>` ospec).

It also uses \beamer@donoframe to suppress unlabeled slides, but it is inefficient (bug #866) compared to \beamer@doseveralframes which does not typeset the skipped content.

Use the following structure instead:

    take \beamer@doseveralframes unless overridden below:
    if allowframebreaks
        if ospec not empty
            \beamer@autobreakframe
        # else keep \beamer@doseveralframes
        fi
    fi
    if fragile
        \beamer@doexternalframe
    fi
    if fragile=singleslide
        if ospec not empty
            \beamer@dosingleframe
        else
            \beamer@donoframe
        fi
    fi

Fixes #866.
Fixes #872.
Fixes #873.

### CODE REVIEW

**Comment by samcarter** [comment]
Thanks for your PR! As this is like an open-heart-surgery on beamer, I'll do a bit of testing before merging.

**Comment by josephwright** [comment]
I think this PR needs both @samcarter  and I to read carefully. What we definitely should do is tidy up coding in such changes: for example, `%` should only be at the end of the lines where it's needed.

**Comment by samcarter** [comment]
There might be some difference in the handling of againframes, unfortunately the git history does not go back far enough to see why this was introduced...

**Comment by josephwright** [comment]
> There might be some difference in the handling of againframes, unfortunately the git history does not go back far enough to see why this was introduced...

You reading Till's commits ;)

**Comment by samcarter** [comment]
> > There might be some difference in the handling of againframes, unfortunately the git history does not go back far enough to see why this was introduced...
> 
> You reading Till's commits ;)

The ones with `*** empty log message ***` are the most helpful ones :)

**Comment by amonakov** [comment]
Can you share your thoughts so far, please?

**Comment by samcarter** [comment]
My thoughts so far are that it seems that there is a difference how again frames are treated, but I haven't yet found an example where this causes a problem.

My proposal would be to merge this into the main branch and keep testing it until after the TL24 code freeze. 

@josephwright  What do you think?

**Comment by amonakov** [comment]
> @josephwright What do you think?

Let me point out he thumbed up your response (Github doesn't send out notifications in such cases afaik).

**Pull request merged**
