### PR TITLE
add template to switch between frame/page number formats in footline

### PR DESCRIPTION
**Pull request by ghost**
Related to https://github.com/josephwright/beamer/commit/428227937352f4d037952fc09b2beab52d7034c0#commitcomment-26606362

This would be my suggestion to simplify changing between different frame/page number formats. Without redefining the whole footline template, one could now simply do

```
\usetheme{Boadilla}

\setbeamertemplate{framenumber in foot}[framenumber] % displays the current frame number
%\setbeamertemplate{framenumber in foot}[totalframenumber] % displays the current frame number / total frame number
%\setbeamertemplate{framenumber in foot}[appendixframenumber] % replicates behaviour of the appendixnumbeerbeamer package
%\setbeamertemplate{framenumber in foot}[pagenumber] % displays the current page number
%\setbeamertemplate{framenumber in foot}[totalpagenumber] % displays the current page number / total page number
%\setbeamertemplate{framenumber in foot}{Quack!} % can be modified to whatever...
```

### CODE REVIEW

**Comment by ghost** [comment]
In case this PR gets merged, I would of course modify the documentation accordingly.

**Comment by josephwright** [comment]
@louisstuart96 Any objections to taking this?

**Comment by louisstuart96** [comment]
@josephwright @samcarter8 See my comment in https://github.com/josephwright/beamer/commit/428227937352f4d037952fc09b2beab52d7034c0: I'm seeking a better way to deal with this. Macros designed in this commit like `\insertframenumberinappendix` are way too tricky.

**Comment by louisstuart96** [comment]
Anyway, let's merge this first. I guess a lot of tasks are coming (documentations, default style for this template, etc.)

**Pull request merged**
