### PR TITLE
Add a `s` option to frames, to "stretch" as alternative to t,b,c

### PR DESCRIPTION
**Pull request by kno10**
See also latex \framebox[][s] which is similar, only horizontal. Hence the one-letter abbreviation consistent with t,b,c

This is useful when you want to have contents both top and bottom aligned. You can then simply put a \vfill inbetween to have the first part top aligned, the second part bottom aligned.

Why are t,b,c defined with a `fill` and not a `fil`?

### CODE REVIEW

**Comment by samcarter** [comment]
Interesting idea! However in it's current form, this results in a lot underfull vboxes:

```
\documentclass{beamer}

\makeatletter
\define@key{beamerframe}{s}[true]{% stretch
  \beamer@frametopskip=0pt\relax%
  \beamer@framebottomskip=0pt\relax%
  \beamer@frametopskipautobreak=\beamer@frametopskip\relax%
  \beamer@framebottomskipautobreak=\beamer@framebottomskip\relax%
}
\makeatother

\begin{document}

\begin{frame}[s]
text
\end{frame}	

\end{document}
```

**Comment by kno10** [comment]
Yes, it is not suitable as a default, it only makes sense when you have contents that actually *can* stretch.

**Comment by samcarter** [comment]
To do:

- [x] write documentation
- [ ] ~~make a corresponding documentclass option to be consistent with the other frame options~~ (bottom also does not have a global option)
- [x] update changelog

**Comment by kno10** [comment]
I am not sure what is the best way to avoid the underfull vboxes.

Maybe a tiny fill could be enough to solve this, without being noticable to the typical user:
```
\beamer@framebottomskip=0pt plus 0.01fil\relax%
```
i.e., if there is no other place to fill, fill at the bottom.

**Comment by samcarter** [comment]
@kno10  I like the idea with the tiny fill at the bottom. This should also avoid the text clashing with the navigations symbols.

**Comment by kno10** [comment]
For the other alignments, would it make sense to also use fil instead of fill, to allow \vfill to be stronger?

**Comment by samcarter** [comment]
@kno10 It might have made sense to do this ~ 15 years ago, but I think the change would be too big now because it could significantly change the layout of existing presentations.

**Pull request merged**
